"""add pending_customer_id and pending_identity to chat_sessions

Revision ID: 6936a11647d2
Revises: 36bfe30ad2d1
Create Date: 2026-07-27 13:43:47.709427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6936a11647d2'
down_revision: Union[str, Sequence[str], None] = '36bfe30ad2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('pending_customer_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('pending_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'customers', ['pending_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'pending_identity')
    op.drop_column('chat_sessions', 'pending_customer_id')
    # ### end Alembic commands ###
